export { Avatar } from './Avatar'
export type { AvatarProps } from './Avatar'
export { EllipsisTextWithTooltip } from './EllipsisTooltip'
export type { EllipsisTextWithTooltipProps } from './EllipsisTooltip'
export { NewlineText } from './NewLineText'
export type { NewLineTextProps } from './NewLineText'
